# Generated by Django 4.2.6 on 2024-02-13 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_unit_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_cost_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('received_quantity', models.PositiveIntegerField(default=0, null=True)),
                ('remaining_quantity', models.PositiveIntegerField(default=0, null=True)),
                ('package_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.package')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('invoice_number', models.CharField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=12, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('recieved_at', models.DateField(null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('partially recieved', 'PARTIALLY RECIEVED'), ('recieved', 'RECIEVED')], default='pending', max_length=20, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(through='purchases.OrderedProduct', to='product.product_item')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='suppliers.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchases.purchaseorder'),
        ),
    ]
