# Generated by Django 4.2.6 on 2023-11-06 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_product_item_location'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('package_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.package')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(through='purchases.OrderedProduct', to='product.product_item')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='suppliers.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchases.purchaseorder'),
        ),
    ]
