# Generated by Django 4.2.6 on 2023-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='price',
            new_name='cost_unit_price',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='total_cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
