# Generated by Django 4.2.6 on 2023-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_rename_price_orderedproduct_cost_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
