# Generated by Django 4.2.6 on 2023-11-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_purchaseorder_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('partially recieved', 'PARTIALLY RECIEVED'), ('recieved', 'RECIEVED')], default='pending', max_length=20, null=True),
        ),
    ]
