# Generated by Django 4.2.6 on 2023-11-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_item_barcode'),
        ('purchases', '0007_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='recieved_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.package'),
        ),
    ]
