# Generated by Django 4.2.6 on 2023-11-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_purchaseorder_recieved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
