# Generated by Django 4.2.6 on 2023-11-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_remove_purchaseorder_received_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
