# Generated by Django 4.2.6 on 2023-11-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_orderedproduct_remaining_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.PositiveIntegerField(null=True)),
                ('received_time', models.DateTimeField(auto_now_add=True)),
                ('ordered_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.orderedproduct')),
            ],
        ),
    ]
