# Generated by Django 4.2.6 on 2023-12-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_alter_purchaseorder_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
