# Generated by Django 4.2.6 on 2024-02-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic_print_receipt', models.BooleanField(default=False)),
                ('allow_date_change', models.BooleanField(default=True)),
                ('allow_typeahead', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='pharmacy_email')),
                ('email_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_port', models.CharField(blank=True, max_length=10, null=True)),
                ('email_host_password', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
