# Generated by Django 4.2.6 on 2023-11-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='pharmacy_email')),
                ('email_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_port', models.CharField(blank=True, max_length=10, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
