# Generated by Django 4.2.6 on 2023-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic_print_receipt', models.BooleanField(default=False)),
                ('allow_date_change', models.BooleanField(default=True)),
                ('allow_typeahead', models.BooleanField(default=True)),
            ],
        ),
    ]
