# Generated by Django 4.2.6 on 2023-12-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_appsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbackend',
            name='email_host_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
