# Generated by Django 4.2.6 on 2023-12-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('other_names', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('code', models.CharField(max_length=100, null=True, unique=True)),
                ('phone_number_1', models.CharField(max_length=100, null=True, unique=True)),
                ('phone_number_2', models.CharField(max_length=100, null=True, unique=True)),
                ('website', models.URLField(blank=True, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
