# Generated by Django 4.2.6 on 2023-10-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_item_markup_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_item',
            name='markup_value',
        ),
    ]
