# Generated by Django 4.2.6 on 2023-11-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_item_markup_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_quantity_recieved', models.IntegerField(blank=True, null=True)),
                ('available_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
