# Generated by Django 4.2.6 on 2023-11-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='markup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
