# Generated by Django 4.2.6 on 2023-11-03 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_item_markup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products_item', models.IntegerField(blank=True, null=True)),
                ('package_name', models.CharField(max_length=100, null=True, unique=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_item')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.unit')),
            ],
        ),
    ]
