# Generated by Django 4.2.6 on 2023-11-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='student_barcode/'),
        ),
    ]
