# Generated by Django 4.2.6 on 2023-11-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_item_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
