# Generated by Django 4.2.6 on 2023-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='product_barcode/'),
        ),
    ]
