# Generated by Django 4.2.6 on 2023-11-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_item_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
