# Generated by Django 4.2.6 on 2023-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_item_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product_item',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
