# Generated by Django 4.2.6 on 2023-12-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_package_date_created_product_item_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='available_package_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
