# Generated by Django 4.2.6 on 2023-12-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_item_available_package_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
