# Generated by Django 4.2.6 on 2023-12-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_package_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
