# Generated by Django 4.2.6 on 2024-02-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('authentication', '0001_initial'),
        ('auth', '0028_group_custom_name_group_pharmacy_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pharmacys',
            field=models.ManyToManyField(blank=True, related_name='admin', to='main.pharmacy'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
