# Generated by Django 4.2.6 on 2024-01-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
