# Generated by Django 4.2.6 on 2023-10-31 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('schema_name', models.CharField(db_index=True, max_length=63, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('is_mainbranch', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_admin', to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(related_name='pharmacy_working', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='main.pharmacy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
