# Generated by Django 4.2.6 on 2023-10-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, null=True, unique=True),
        ),
    ]
