# Generated by Django 4.2.6 on 2023-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
