# Generated by Django 4.2.6 on 2023-11-26 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_product_item_available_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('invoice_number', models.CharField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=12, null=True)),
                ('date_created', models.DateField(null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_unit_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_cost_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('package_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.package')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_item')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(through='sales.SaleProduct', to='product.product_item'),
        ),
    ]
