# Generated by Django 4.2.6 on 2023-11-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproduct',
            old_name='purchase_order',
            new_name='sale',
        ),
    ]
