# Generated by Django 4.2.6 on 2023-11-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_purchase_order_saleproduct_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='order_number',
            new_name='sale_number',
        ),
    ]
