# Generated by Django 4.2.6 on 2023-11-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_order_number_sale_sale_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sub_total_cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
