# Generated by Django 4.2.6 on 2023-12-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_tax_alter_sale_discount_alter_sale_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='tax',
        ),
        migrations.AddField(
            model_name='sale',
            name='tax',
            field=models.ManyToManyField(related_name='sale_tax', to='sales.tax'),
        ),
    ]
