# Generated by Django 4.2.6 on 2023-12-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_sale_tax_sale_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_created',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
