# Generated by Django 4.2.6 on 2023-12-02 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_sale_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
