# Generated by Django 4.2.6 on 2023-12-02 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_sale_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='change',
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('change', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sale', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
        ),
    ]
