# Generated by Django 4.2.6 on 2023-12-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_sale_amount_paid_remove_sale_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
    ]
