# Generated by Django 4.2.6 on 2023-12-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_paymentdetails_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
