# Generated by Django 4.2.6 on 2023-12-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_paymentdetails_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='sales.sale'),
        ),
    ]
