# Generated by Django 4.2.6 on 2023-12-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_paymentdetails_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
    ]
