# Generated by Django 4.2.6 on 2023-12-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_paymentdetails_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_item', to='sales.paymentdetails'),
        ),
    ]
