# Generated by Django 4.2.6 on 2023-12-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_paymentdetails_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
