# Generated by Django 4.2.6 on 2023-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_sale_date_created_alter_sale_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
