# Generated by Django 4.2.6 on 2023-12-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_sale_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
