# Generated by Django 4.2.6 on 2023-12-20 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_saleproduct_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sub_total_cost_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='total_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_item', to='sales.paymentdetails'),
        ),
    ]
