# Generated by Django 4.2.6 on 2023-12-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_remove_sale_sub_total_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sub_total_cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
