# Generated by Django 4.2.6 on 2023-11-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedstock',
            name='received_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivedstock',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
