# Generated by Django 4.2.6 on 2023-11-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_item_available_quantity'),
        ('stock', '0003_stockentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='previous_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='quantity_received',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_item'),
        ),
    ]
