# Generated by Django 4.2.6 on 2023-11-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_stockentry_price_remove_stockentry_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
