# Generated by Django 4.2.6 on 2023-11-17 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_item_available_quantity'),
        ('stock', '0005_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.package'),
        ),
    ]
