# Generated by Django 4.2.6 on 2023-11-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockentry_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='package_type',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
