# Generated by Django 4.2.6 on 2023-11-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stockentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
