# Generated by Django 4.2.6 on 2023-11-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stockentry_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='reanson',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='ReceivedStock',
        ),
    ]
