# Generated by Django 4.2.6 on 2023-12-14 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_package_date_created_product_item_date_created'),
        ('stock', '0011_rename_reanson_stockentry_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.package'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
